# Generated by Django 4.1.7 on 2023-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_question',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
