# Generated by Django 4.1.7 on 2023-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0004_message_is_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
