# Generated by Django 4.1.7 on 2023-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0007_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='context',
            field=models.JSONField(default=list),
        ),
    ]
