# Generated by Django 4.1.7 on 2023-06-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0008_chat_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
